In [2]:
print("hello")

hello


In [3]:
a=10
b=20
print(a+b)

30


In [4]:
a=10
b=20
a+b
a

10

In [5]:
var1=input("Enter a number")

In [6]:
import numpy

In [7]:
import numpy as np

In [8]:
arr1=np.array([1,2,3,4,5])
arr1.ndim
arr1+1

array([2, 3, 4, 5, 6])

In [9]:
arr1[-1]=6
arr1

array([1, 2, 3, 4, 6])

In [10]:
arr1[:]=10
arr1

array([10, 10, 10, 10, 10])

In [11]:
arr1=4
arr1


4

In [12]:
arr1=np.array([1,2,3,4,5])
arr2=arr1*10
arr2

array([10, 20, 30, 40, 50])

In [13]:
arr1[2:4]=[20,30]
arr1

array([ 1,  2, 20, 30,  5])

In [14]:
arr1.shape

(5,)

In [15]:
arr1=np.array([1,2,3,4,5,"hello"])
arr1

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [16]:
arr1=np.array([1,2,3,4,5,True,False])
arr1

array([1, 2, 3, 4, 5, 1, 0])

In [17]:
arr2=np.array([[1,2,3,4],[5,2,3,1],[3,2,1,2]])
arr2.shape

(3, 4)

In [18]:
arr2=np.array([[1,2,3,4],[5,2,3,1],[3,2,1,2],[3,4,2,3]])
arr2.shape
arr2.size
arr2.dtype

dtype('int64')

In [19]:
arr2=np.array([[1,2,3,4],[5,2,3,1],[3,2000,1,2],[3,4,2,3]])
arr2[1:3,1:3]=0
arr2

array([[1, 2, 3, 4],
       [5, 0, 0, 1],
       [3, 0, 0, 2],
       [3, 4, 2, 3]])

In [20]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
arr2[:,::2]
arr2[::6,::2]=-1
arr2


array([[-1,  2, -1],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [-1, 20, -1]])

Advance Indexing

In [21]:
arr2[[0,1,5],[1,1,1]]=[1,2,3]
arr2

array([[-1,  1, -1],
       [ 4,  2,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16,  3, 18],
       [-1, 20, -1]])

In [22]:
arr2[[3,4,5],[0,1,2]]=[-1,-2,-3]
arr2

array([[-1,  1, -1],
       [ 4,  2,  6],
       [ 7,  8,  9],
       [-1, 11, 12],
       [13, -2, 15],
       [16,  3, -3],
       [-1, 20, -1]])

In [23]:
arr2[[0,1,4]]=255
arr2

array([[255, 255, 255],
       [255, 255, 255],
       [  7,   8,   9],
       [ -1,  11,  12],
       [255, 255, 255],
       [ 16,   3,  -3],
       [ -1,  20,  -1]])

In [24]:
arr2[:,0:2]=255
arr2

array([[255, 255, 255],
       [255, 255, 255],
       [255, 255,   9],
       [255, 255,  12],
       [255, 255, 255],
       [255, 255,  -3],
       [255, 255,  -1]])

In [25]:
arr2[arr2%2==0]=0
arr2

array([[255, 255, 255],
       [255, 255, 255],
       [255, 255,   9],
       [255, 255,   0],
       [255, 255, 255],
       [255, 255,  -3],
       [255, 255,  -1]])

In [26]:
arr2=np.random.randint(1,100,(7,3))
arr2

array([[43,  3, 49],
       [45, 88, 73],
       [90, 42, 80],
       [80, 26, 82],
       [90, 71, 87],
       [77, 18,  5],
       [44, 66, 24]], dtype=int32)

In [27]:
arr2[arr2%2==0]=0
arr2

array([[43,  3, 49],
       [45,  0, 73],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0, 71, 87],
       [77,  0,  5],
       [ 0,  0,  0]], dtype=int32)

In [28]:
import numpy as np  
arr = np.array([12, 45, 7, 19, 34, 28, 90, 55, 63])
arr[arr>30]
arr[arr%2!=0]
arr[arr%5==0]=-1
arr
arr = np.array([12, 45, 7, 19, 34, 28, 90, 55, 63])
np.sum(arr<50)

np.int64(6)

In [29]:

arr = np.array([[10, 25, 40], [55, 18, 72], [91, 30, 64]])
arr[arr>50]
arr[arr%2==0]=0
arr
arr = np.array([[10, 25, 40], [55, 18, 72], [91, 30, 64]])
np.sum(arr[arr%5==0])
arr = np.array([[10, 25, 40], [55, 18, 72], [91, 30, 64]])
len(arr[(arr>20) & (arr<70)])


5

In [30]:
arr = np.array([[12, 34, 56],[78, 90, 23],[45, 67, 89]])
arr[0:3:2]
arr = np.array([[12, 34, 56],[78, 90, 23],[45, 67, 89]])
arr[:,1]
arr = np.array([[12, 34, 56],[78, 90, 23],[45, 67, 89]])
arr[[0,1,2],[0,1,1]]
arr = np.array([[12, 34, 56],[78, 90, 23],[45, 67, 89]])
arr[[2,1,0],:]
import numpy as np
arr = np.array([[12, 34, 56],[78, 90, 23],[45, 67, 89]])
arr[[0,2]]=arr[[2,0]]
arr

array([[45, 67, 89],
       [78, 90, 23],
       [12, 34, 56]])

In [31]:
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
arr[(arr%5==0) & (arr>30)]
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
arr[arr<50]=-1
arr
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
arr[:,2:]=100
arr
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
arr[arr>60]*= 2
arr

array([[  5,  15,  25],
       [ 35,  45,  55],
       [130, 150, 170]])

In [37]:
arr = np.array([[5, 15, 25],[35, 45, 55],[65, 75, 85]])
np.sum(arr,axis=1)
np.sum(arr,axis=0)
np.min(arr,axis=0)
np.max(arr,axis=1)
np.argmax(arr,axis=1)
np.argmax(arr,axis=0)

array([2, 2, 2])

In [56]:
np.zeros((7,5))
np.ones((5,3))
np.full((3,3),7)
a=np.full((5,3),7)
np.full_like(a,5)
np.arange(1,10,1)
np.arange(100,0,-10)
b=np.arange(100,0,-1)
b.reshape((10,10))
b.reshape((25,4))
np.reshape(arr,(9,))
np.reshape(arr,(3,3))
np.random.randint(1,1000,(10,5))
np.random.random((10,5))
np.random.randint(1,3,(10,5))

array([[2, 1, 2, 1, 1],
       [2, 2, 2, 2, 1],
       [1, 2, 1, 2, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 2, 2, 1],
       [1, 2, 1, 2, 2],
       [2, 2, 2, 1, 2],
       [1, 1, 1, 2, 1],
       [1, 1, 2, 2, 1],
       [2, 1, 2, 2, 1]], dtype=int32)